CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    full_name VARCHAR(120),
    headline VARCHAR(160),
    bio VARCHAR(3000),
    profile_image_url VARCHAR(500),
    location VARCHAR(120),
    phone VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(80) NOT NULL,
    category VARCHAR(80)
);
CREATE INDEX idx_skills_user_id ON skills(user_id);

CREATE TABLE educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    institution VARCHAR(180) NOT NULL,
    degree VARCHAR(120) NOT NULL,
    field_of_study VARCHAR(120),
    start_date VARCHAR(20),
    end_date VARCHAR(20),
    description VARCHAR(2000)
);
CREATE INDEX idx_educations_user_id ON educations(user_id);

CREATE TABLE experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    company VARCHAR(180) NOT NULL,
    position VARCHAR(140) NOT NULL,
    location VARCHAR(120),
    start_date VARCHAR(20),
    end_date VARCHAR(20),
    currently_working BOOLEAN NOT NULL,
    description VARCHAR(3000)
);
CREATE INDEX idx_experiences_user_id ON experiences(user_id);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(120) NOT NULL,
    short_description VARCHAR(300),
    description VARCHAR(4000),
    image_url VARCHAR(500),
    github_url VARCHAR(500),
    live_url VARCHAR(500),
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_projects_user_id ON projects(user_id);

CREATE TABLE project_technologies (
    project_id BIGINT NOT NULL REFERENCES projects(id),
    technology VARCHAR(60) NOT NULL
);
CREATE INDEX idx_project_technologies_project_id ON project_technologies(project_id);

CREATE TABLE social_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    platform VARCHAR(60) NOT NULL,
    url VARCHAR(500) NOT NULL
);
CREATE INDEX idx_social_links_user_id ON social_links(user_id);

CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    title VARCHAR(120) NOT NULL,
    slug VARCHAR(90) NOT NULL UNIQUE,
    template VARCHAR(30) NOT NULL,
    is_published BOOLEAN NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
